### ISSUE TITLE
Save the kite model that was used in the meta data of the log file

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteUtils.jl#42]
- [ ] improve save_log()
- [ ] improve load_log()
- [ ] add function kitemodel(log)
